version: "3.9"
services:
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-storage:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: "mlops-sucker"
      MINIO_ROOT_PASSWORD: "i-love-mlops"
    command: server --console-address ":9090" /data
    restart: always # necessary since it's failing to start sometimes
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      RUNTIME_DC: true
      MONGO_HOST: "mongo"
      MINIO_HOST: "minio"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'

volumes:
  minio-storage:
  mongo:
