linearSVC:
  model_path_template: "models/linearSVC_{}.pk"
  tfidf:
    _target_: sklearn.feature_extraction.text.TfidfVectorizer
  model:
    _target_: sklearn.svm.LinearSVC
    C: 0.01
logreg:
  model_path_template: "models/logreg_{}.pk"
  tfidf:
    _target_: sklearn.feature_extraction.text.TfidfVectorizer
  model:
    _target_: sklearn.linear_model.LogisticRegression
    C: 0.05